version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=bird
      - PORT=3000
    stdin_open: true
    tty: true

volumes:
  mongodb: